In [5]:
import cv2
img = cv2.imread("floor_plan2", 0)
rows,cols = img.shape



for i in range (rows): 
    for j in range (cols):
        print(img[i][j])

AttributeError: 'NoneType' object has no attribute 'shape'

In [12]:
import cv2
import numpy as np



x = np.random.randint(0,255,(rows,cols))
img = cv2.imread('floor_plan2.jpg',0)
rows,cols = img.shape

for i in range(rows):
    for j in range(cols):
        k = x[i,j]
        

In [13]:
x


array([[ 35,  63,  90, ..., 246, 151, 117],
       [192, 143,   4, ..., 123, 202, 195],
       [ 68,  50, 107, ...,  57,  66, 194],
       ...,
       [133,  16,  56, ..., 225, 205, 206],
       [245, 219, 136, ...,  87, 134,  48],
       [ 38,  73, 159, ..., 209,  14,  78]])

In [44]:
from __future__ import print_function
import matplotlib.pyplot as plt
 
class AStarGraph(object):
    #Define a class board like grid with two barriers
 
    def __init__(self):
        self.barriers = []
        for i in obs:
            self.barriers.append(i)
 
    def heuristic(self, start, goal):
        #Use Chebyshev distance heuristic if we can move one square either
        #adjacent or diagonal
        D = 1
        D2 = 1
        dx = abs(start[0] - goal[0])
        dy = abs(start[1] - goal[1])
        return D * (dx + dy) + (D2 - 2 * D) * min(dx, dy)
 
    def get_vertex_neighbours(self, pos):
        n = []
        #Moves allow link a chess king
        for dx, dy in [(1,0),(-1,0),(0,1),(0,-1),(1,1),(-1,1),(1,-1),(-1,-1)]:
            x2 = pos[0] + dx
            y2 = pos[1] + dy
            if x2 < 0 or x2 > 7 or y2 < 0 or y2 > 7:
                continue
            n.append((x2, y2))
        return n
 
    def move_cost(self, a, b):
        for barrier in self.barriers:
            if b in barrier:
                return 100 #Extremely high cost to enter barrier squares
        return 1 #Normal movement cost
    
 
def AStarSearch(start, end, graph):
 
    G = {} #Actual movement cost to each position from the start position
    F = {} #Estimated movement cost of start to end going via this position
 
    #Initialize starting values
    G[start] = 0 
    F[start] = graph.heuristic(start, end)
 
    closedVertices = set()
    openVertices = set([start])
    cameFrom = {}
 
    while len(openVertices) > 0:
        #Get the vertex in the open list with the lowest F score
        current = None
        currentFscore = None
        for pos in openVertices:
            if current is None or F[pos] < currentFscore:
                currentFscore = F[pos]
                current = pos
 
        #Check if we have reached the goal
        if current == end:
            #Retrace our route backward
            path = [current]
            while current in cameFrom:
                current = cameFrom[current]
                path.append(current)
            path.reverse()
            return path, F[end] #Done!
 
        #Mark the current vertex as closed
        openVertices.remove(current)
        closedVertices.add(current)
 
        #Update scores for vertices near the current position
        for neighbour in graph.get_vertex_neighbours(current):
            if neighbour in closedVertices: 
                continue #We have already processed this node exhaustively
            candidateG = G[current] + graph.move_cost(current, neighbour)
 
            if neighbour not in openVertices:
                openVertices.add(neighbour) #Discovered a new vertex
            elif candidateG >= G[neighbour]:
                continue #This G score is worse than previously found
 
            #Adopt this G score
            cameFrom[neighbour] = current
            G[neighbour] = candidateG
            H = graph.heuristic(neighbour, end)
            F[neighbour] = G[neighbour] + H
 
    raise RuntimeError("A* failed to find a solution")
 
if __name__=="__main__":
    graph = AStarGraph()
    result, cost = AStarSearch((0,0), (100,50), graph)
    print ("route", result)
    print ("cost", cost)
    plt.plot([v[0] for v in result], [v[1] for v in result])
    for barrier in graph.barriers:
        plt.plot([v[0] for v in barrier], [v[1] for v in barrier])
    plt.xlim(0,800)
    plt.ylim(0,600)
    plt.show()

RuntimeError: A* failed to find a solution

In [1]:
from PIL import Image

In [29]:
im = Image.open("floor_plan.png","r")

In [3]:
import numpy as np

In [30]:
print(im)

<PIL.PngImagePlugin.PngImageFile image mode=RGBA size=800x541 at 0x7F329B229290>


In [31]:
pix_val = np.array(im.getdata())

In [32]:
print(pix_val)

[[255 255 255 255]
 [255 255 255 255]
 [255 255 255 255]
 ...
 [255 255 255 255]
 [255 255 255 255]
 [255 255 255 255]]


In [33]:
print(pix_val[:,1])

[255 255 255 ... 255 255 255]


In [34]:
pix_val = pix_val[:,1]

In [35]:
print(pix_val)

[255 255 255 ... 255 255 255]


In [36]:
print(len(pix_val))

432800


In [38]:
pix_val = pix_val.reshape(541,800)

In [39]:
print(pix_val)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [41]:
rows,cols = pix_val.shape

In [42]:
obs = []
for i in range(rows):
    for j in range(cols):
        if pix_val[i,j]<240:
            obs.append((i,j))

In [15]:
print(obs)

[(1, 16), (1, 17), (1, 18), (1, 19), (1, 20), (1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 26), (1, 27), (2, 15), (2, 16), (2, 17), (2, 18), (2, 19), (2, 20), (2, 21), (2, 22), (2, 23), (2, 24), (2, 25), (2, 26), (2, 27), (3, 10), (3, 13), (3, 15), (3, 16), (3, 17), (3, 18), (3, 19), (3, 20), (3, 21), (3, 22), (3, 23), (3, 24), (3, 25), (3, 26), (3, 27), (3, 28), (3, 29), (3, 30), (3, 31), (4, 12), (4, 13), (4, 14), (4, 15), (4, 16), (4, 17), (4, 18), (4, 19), (4, 20), (4, 21), (4, 22), (4, 23), (4, 24), (4, 25), (4, 26), (4, 27), (4, 28), (4, 29), (4, 30), (4, 31), (4, 95), (4, 96), (5, 12), (5, 13), (5, 14), (5, 15), (5, 25), (5, 26), (5, 28), (5, 29), (5, 30), (5, 32), (5, 95), (5, 96), (6, 11), (6, 12), (6, 13), (6, 14), (6, 15), (6, 25), (6, 29), (6, 30), (6, 31), (6, 32), (6, 33), (6, 96), (7, 10), (7, 11), (7, 12), (7, 13), (7, 14), (7, 21), (7, 22), (7, 29), (7, 30), (7, 31), (7, 32), (7, 33), (7, 95), (7, 96), (8, 11), (8, 12), (8, 13), (8, 21), (8, 22), (8, 30), (8, 31), 